name: Daily Weather Bot

on:
  schedule:
    - cron: '0 21 * * *' # 5 AM HK
    - cron: '0 13 * * *' # 9 PM HK
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必須要有寫入權限
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run Bot
        run: python weather_script.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add subscribers.json
          git commit -m "Update subscribers list" || exit 0
          git push
